### PR TITLE
Meta-121 crosslinks

### PR DESCRIPTION
**Pull request by lennertvandevelde**

### CODE REVIEW

**Review by mielvds — APPROVED** [review]
@lennertvandevelde looks good! just as a sidenote: you don't have to copy files, not even before a large refactoring, that what git is for! You can always go back in the history if things go wrong. 

I merged the two files and did some code formatting. I was not able to test it though. Can you add some info on how to run it to the README?

**Review by milvala — APPROVED** [review]

**Comment by mielvds** [comment]
@lennertvandevelde this is looking good! The ony thing I would suggest is to change the crosslink config format to a less error-prone syntax like json or yaml like `{ "name":[file1, file2]}`

**Comment by lennertvandevelde** [comment]
> @lennertvandevelde this is looking good! The ony thing I would suggest is to change the crosslink config format to a less error-prone syntax like json or yaml like `{ "name":[file1, file2]}`
> 
> Is this CLI argument pointing to a file or is the value supposed to be given inline?

Right now it is supposed to be given inline, but with different formats I would let it point to a file to keep the command a bit clear.

**Comment by mielvds** [comment]
Ah I see, then the syntax is fine (You can consider doing `name=file1;file2` to make it a bit more clear). 

And is it then `--crosslinks "name1;file1;file2;..." --crosslinks "name2;file3;file4;..."` or `--crosslinks "name1;file1;file2;... \n name2;file3;file4;..."`

**Comment by lennertvandevelde** [comment]
The latter form should be used now. I will however try and change some more things of the syntax, because unquoted, bash interprets the ';' as a newline.

**Pull request merged**
